### ISSUE TITLE
"None" parsing error

### ISSUE THREAD

**Issue by tomtau** [informalsystems/atomkraft#208] opened 2023-01-12 09:55 UTC
I was trying to make a small modification of https://github.com/informalsystems/atomkraft/tree/dev/examples/cosmos-sdk/transfer to make it for x/nft (non-fungible tokens). Here's the modified module (not sure if correct yet, I'm fairly new to TLA):
```tla
------- MODULE nft -------
EXTENDS Variants, Integers

VARIABLES
    \* @typeAlias: ACCOUNT = Str;
    \* @typeAlias: DENOM_ID = Str;
    \* @typeAlias: TOKEN_ID = Str;
    \* @type: ACCOUNT -> DENOM_ID -> Set(TOKEN_ID);
    balances,
    \* @type: Init({wallets: Set(ACCOUNT)}) | TransferNft({sender: ACCOUNT, receiver: ACCOUNT, denom: DENOM_ID, token: TOKEN_ID});
    action,
    \* @type: Int;
    step

WALLETS == {"Alice", "Bob"}
DENOMS == {"token1"}

Init ==
    /\ balances = [wallet \in WALLETS |-> [denom \in DENOMS |-> IF wallet \in {"Alice"} THEN {"token1"} ELSE {}]]
    /\ action = Variant("Init", [wallets |-> WALLETS])
    /\ step = 0

Next ==
    \E sender \in WALLETS:
    \E receiver \in WALLETS:
    \E denom \in 1..balances[sender]:
    \E token \in denom[token]:
        /\ sender /= receiver
        /\ balances' = [
            balances EXCEPT
            ![sender][denom] = @ \ {token},
            ![receiver][denom] = @ \union {token}
            ]
        /\ action' = Variant("TransferNft", [sender |-> sender, receiver |-> receiver, denom |-> denom, token |-> token])
    /\ step' = step + 1

View ==
    TransferNft(
        "Transfer",
        action,
        [sender |-> "", receiver |-> "", denom |-> "", token |-> ""]
    )

TestAliceZero == balances["Alice"]["denom1"] = {}

====
```

When I try to do any model operation (e.g. `atomkraft model load models/nft.tla`), it'll get a "None" parsing error:
```
Loading models/nft.tla... 
Parsing error 💥
Parse error at .../models/nft.tla:
None
```

In VScode,  I get a red squiggly line on the first character (Ln 1, Col 1) with the error message:
```
Cannot find source file for module Variants imported in module Nft.
```

The original transfer module worked for me fine. I probably did something wrong, but the "None" error message isn't very helpful.

**Comment by ivan-gavran** [comment] 2023-01-12 16:18
Hi @tomtau ! Agree that the error message is not really helpful -> it will be addressed once [this issue](https://github.com/informalsystems/modelator/issues/297) is resolved.

In the meantime, probably the best way to get better error messages is by using Apalache directly.
By running `atomkraft model apalache info` you will get the info on where it is on your system, and then you can run `apalache parse models/nft.tla` and `apalache typecheck models/nft.tla` (after adding the path of the folder containing apalache to your PATH variable).

In the concrete case, I believe the problem is at the line `\E token \in denom[token]:`: `token` is just introduced by the quantifir so it's not clear what `denom[token]` is. What did you try to achieve there?

**Comment by tomtau** [comment] 2023-01-13 02:51
@ivan-gavran thanks, running Apalache directly indeed produces more helpful error messages! the issue was with `View ==` where it should have been:
```
View ==
    VariantGetOrElse(
        "TransferNft",
...
```
for the denom, I rewrote it as:
```
    \E denom \in DENOMS:
    \E token \in balances[sender][denom]:
```

It seems to load fine now. Should I keep this issue open (for unhelpful parsing error messages), or close it as it's subsumed by https://github.com/informalsystems/modelator/issues/297 ? And for any further Atomkraft/Apalache questions, shall I open issues here or is there a better venue for it (e.g. Cephalopod Discord)?

**Comment by rnbguy** [comment] 2023-01-13 10:11
@tomtau thanks for the issue report :slightly_smiling_face: I will close this issue as a duplicate of the modelator issue. 

We are currently using apalache CLI to communicate - which lacks a standard parsing format. So, we may have missed some error cases in the parser. When apalache-chai is integrated, atomkraft will use its proper API to communicate success and errors.

Duplicate of informalsystems/modelator#297

PS. I started the process to add you to our slack channel :partying_face:

**Closed as completed** 2023-01-13 10:11 UTC
