### ISSUE TITLE
`atomkraft reactor` generates methods with same names

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/atomkraft#44] opened 2022-07-25 12:49 UTC
`atomkraft reactor --actions "fizz,fuzz,fizzfuzz"  --variables "x,y"`generates the following code.

`act_step` should be different for each method.

```
import time
import pytest
from cosmos_net.pytest import Testnet
from modelator.pytest.decorators import step

    
keypath = 'action'



@pytest.fixture
def state():
    return {}


@step('fizz')
def act_step(testnet, state, x, y):
    print("Step: fizz")


@step('fuzz')
def act_step(testnet, state, x, y):
    print("Step: fuzz")


@step('fizzfuzz')
def act_step(testnet, state, x, y):
    print("Step: fizzfuzz")
```

**Comment by andrey-kuprianov** [comment] 2022-07-26 08:55
Duplicate of #34 
@rnbguy next time please check whether a similar issue exists already;)

**Closed as completed** 2022-07-28 08:24 UTC
Labels: enhancement
