### ISSUE TITLE
Testnet creation fails non-deterministically

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/atomkraft#58] opened 2022-07-27 08:53 UTC
I have the Atomkraft project configured correctly, with all binaries and everything. This is the [CosmWasm counter example](https://github.com/informalsystems/atomkraft/blob/41ee194af384c6776b4229290a022a7f5bca14a3/examples/cosmwasm/counter/README.md). Most of the time testing works fine using this example; but from time to time it fails like that (from a pytest execution):

```sh
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/modelator/pytest/decorators.py:78: in <dictcomp>
    arg: step[arg] if arg in step else request.getfixturevalue(arg)
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py:554: in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py:573: in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py:659: in _compute_fixture_value
    fixturedef.execute(request=subrequest)
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py:1057: in execute
    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/pluggy/_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/pluggy/_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py:1111: in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/_pytest/fixtures.py:883: in call_fixture_func
    fixture_result = next(generator)
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/atomkraft/chain/pytest.py:13: in testnet
    testnet.oneshot()
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/atomkraft/chain/testnet.py:214: in oneshot
    self.prepare()
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/atomkraft/chain/testnet.py:182: in prepare
    node.add_key(self.validators[i])
../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/atomkraft/chain/node.py:112: in add_key
    stdout, stderr = self._execute(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <atomkraft.chain.node.Node object at 0x121a0f850>
args = ['keys', 'add', 'validator-0', '--recover', '--keyring-backend', 'test', ...]

    def _execute(self, args, *, stdin: bytes | None = None, stdout=None, stderr=None):
        final_args = f"{self.binary} --home {self.home_dir}".split() + args
        # print(" ".join(final_args))
        stdin_pipe = None if stdin is None else PIPE
        with Popen(final_args, stdin=stdin_pipe, stdout=stdout, stderr=stderr) as p:
            out, err = p.communicate(input=stdin)
            rt = p.wait()
            if rt != 0:
>               raise RuntimeError(f"Non-zero return code {rt}\n{err.decode()}")
E               RuntimeError: Non-zero return code 1
E               Error: aborted
E               Usage:
E                 junod keys add <name> [flags]
E               
E               Flags:
E                     --account uint32           Account number for HD derivation
E                     --algo string              Key signing algorithm to generate keys for (default "secp256k1")
E                     --coin-type uint32         coin type number for HD derivation (default 118)
E                     --dry-run                  Perform action, but don't add key to local keystore
E                     --hd-path string           Manual HD Path derivation (overrides BIP44 config)
E                 -h, --help                     help for add
E                     --index uint32             Address index number for HD derivation
E                 -i, --interactive              Interactively prompt user for BIP39 passphrase and mnemonic
E                     --ledger                   Store a local reference to a private key on a Ledger device
E                     --multisig strings         List of key names stored in keyring to construct a public legacy multisig key
E                     --multisig-threshold int   K out of N required signatures. For use in conjunction with --multisig (default 1)
E                     --no-backup                Don't print out seed phrase (if others are watching the terminal)
E                     --nosort                   Keys passed to --multisig are taken in the order they're supplied
E                     --pubkey string            Parse a public key in JSON format and saves key info to <name> file.
E                     --recover                  Provide seed phrase to recover existing key instead of creating
E               
E               Global Flags:
E                     --home string              The application home directory (default "/Users/andrey/.juno")
E                     --keyring-backend string   Select keyring's backend (os|file|test) (default "test")
E                     --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
E                     --log_format string        The logging format (json|plain) (default "plain")
E                     --log_level string         The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
E                     --output string            Output format (text|json) (default "text")
E                     --trace                    print out full stack trace on errors

../../../Library/Caches/pypoetry/virtualenvs/atomkraft-9j0E0YDD-py3.10/lib/python3.10/site-packages/atomkraft/chain/node.py:238: RuntimeError
```

Not sure what causes that, but would be nice to investigate.

**Comment by andrey-kuprianov** [comment] 2022-07-27 09:46
It turns out it is not such a rare scenario, when multiple tests execute in order...

```sh
FAILED tests/test_traces_example0_itf_json_2022_07_26T12_15_58_262.py::test_trace - RuntimeError: Non-zero retur...
FAILED tests/test_traces_example0_itf_json_2022_07_26T13_08_07_508.py::test_trace - RuntimeError: Non-zero retur...
FAILED tests/test_traces_example0_itf_json_2022_07_26T13_09_28_584.py::test_trace - RuntimeError: Non-zero retur...
FAILED tests/test_traces_example0_itf_json_2022_07_26T13_12_13_736.py::test_trace - RuntimeError: Non-zero retur...
FAILED tests/test_traces_example0_itf_json_2022_07_26T13_17_03_671.py::test_trace - RuntimeError: Non-zero retur...
FAILED tests/test_traces_example0_itf_json_2022_07_26T13_41_16_408.py::test_trace - RuntimeError: Non-zero retur...
FAILED tests/test_traces_example0_itf_json_2022_07_27T09_08_03_748.py::test_trace - RuntimeError: Non-zero retur...
FAILED tests/test_traces_example0_itf_json_2022_07_27T09_37_47_347.py::test_trace - RuntimeError: Non-zero retur...
```

So this needs to be addressed before the prototype release.

**Comment by rnbguy** [comment] 2022-08-12 08:40
I tried to reproduce this bug but with no success. I even ran multiple runs overnight on a macOS instance.

Maybe you can try debugging the final commands for the chain binary on your side. You need to uncomment this print statement.

https://github.com/informalsystems/atomkraft/blob/73f3b0483952d7b4e71f06e7e23478d85deba251/atomkraft/chain/node.py#L187-L190

I used `junod` and `wasmd` compiled from their latest commits. I don't know if this bug manifests using different commits. In that case, it is not a bug in Atomkraft.

**Comment by rnbguy** [comment] 2022-09-08 11:29
@andrey-kuprianov I believe, you have executed many tests on Atomkraft testnet by now, and probably this error did not come up again.

Feel free to close this issue with a comment from your side 🙂

**Comment by ivan-gavran** [comment] 2022-10-10 11:36
@rnbguy could not reproduce the bug

**Closed as not planned by ivan-gavran** 2022-10-10 11:36 UTC
Labels: bug
